### PR TITLE
For convenient experiment setting, propose useful example of `main.py` and `main.json`

### PR DESCRIPTION
**Pull request by raymin0223**
It is related to #15 issue!

### CODE REVIEW

**Comment by raymin0223** [comment]
Any more convenient solution for experiment setting example, plz comment!

And I don't know where to  put `aux.py` file. 
It has `Aux` class that load json file by using **namedtuple object_hook**.
User can load config files by using **. parsing** (ex. opt.data.dataset), not **[] dict parsing** (ex. opt[data][dataset]).

**Comment by raymin0223** [comment]
I change `namedtuple` object_hook to **manual class `DictWithAttributeAccess`**.
Because in namedtuple object, we can not use `.get('something', default)` dictionary method.

It is more convenient on config file. 
We don't need to write useless config part by using `get` method.
For example, look line 42 in `main.py`  (**`if opt.scheduler.get("enabled", False):`**)

**Comment by raymin0223** [comment]
I commit some solutions about #19 (want to use MultiStepLR scheduler) and #20 (fix error to use any optimizer or criterion) issues!

**Comment by kimbob13** [comment]
I think it is good to change the name of aux.py and class in it, so that anyone can know what this module exactly do.
Other than that, it seems no problem to merge this.

**Comment by raymin0223** [comment]
Umm.. do you have any idea of class name?
It's the convention I used for my intern, so I can't think of anything else...
And also, where do you think the most place to put that `Aux.py`?

**Comment by kimbob13** [comment]
Hmm.. config_loader or something like that..?
And, in case of placement, I think we should make general **utils** directory to contain all of these stuffs..

**Pull request merged**
